run:
  skip-dirs:
    - api
    - ui
    - dist
  timeout: 5m

linters-settings:
  golint:
    min-confidence: 0.1
  goimports:
    local-prefixes: github.com/apiclarity/speculator
  errorlint:
    # Check whether fmt.Errorf uses the %w verb for formatting errors. See the readme for caveats
    errorf: false

linters:
  enable-all: true
  disable:
    - maligned
    - funlen
    - dupl
    - nestif
    - wsl
    - lll
    - interfacer
    - exhaustivestruct
    - nlreturn
    - gocritic
    - gochecknoglobals
    - testpackage
    - scopelint # deprecated
    - golint # deprecated

    # TODO:(fixme)
    - gocognit
    - godox
    - revive
    - cyclop
    - goerr113
    - tagliatelle
    - prealloc
    - paralleltest
    - structcheck

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - govet